Feature/realtime transactions callback update
ElrondNetwork/dapp-template pull request #33
Opened 2022-02-10 15:28 UTC by MiroMargineanu

2022-02-10 15:50 UTC, StanislavSava requested changes

2022-02-10 15:50 UTC, StanislavSava commented on package.json
> +    "@elrondnetwork/erdjs": "^9.0.3",
let's drop the caret

2022-02-10 15:50 UTC, StanislavSava commented on src/pages/Dashboard/Transactions/index.tsx
> +  React.useEffect(fetchData, [successful]);
pass in the hasActiveTransactions here too

2022-02-11 10:30 UTC, arhtudormorar approved these changes

2022-02-11 10:31 UTC, merged